#!/usr/bin/env python3
from final_encode_decode import decode

# The two keys provided by the user
key1 = "VlVaYWIwMXJNVk1oYVJuQnJaV3R3QU5WWXlNVlpsYkVScFhZVVJLVGxZeUtVbUZVTUZKS1RWRVprZFZvemNHbFNSYldoU1ZGWmFkMU1kdFVqWlRiV3hZQVltMTBObFpyV21SOVdNREZWVkd4d0tWR0ZyY0ZOV01uRWhPWlcxT1IyRkdSYkU1V01YQmhWa01aU1MwNVdaSE5hQU0zQlNWbTFuTVZSUldhR0ZYYXpsRktVMnhhV0dKck1URVk9"
key2 = "V2tkNGJrOVZNVk1oYVJuQnFZV3R2QWVsWXlNVlpsYlZSSnpZVVZhVGxZeUtVbUZVYkZKS1RrRVprZFZvemNGWlNSYldoNlZGWmFkMU1kc2JIRlRhazVZQVltMTBObFp0ZUdSOVdWVEZWVkd4d0tWbFpGY0V4V01uRWhPWld4a1IyRklSWkU1V01YQmhXbE1aU1MxUnNaSE5hQU0zQnNWbTFvUTFSUldhR0ZYYkZwVktVMVJTV0dKck1URVk9"

# Examine the decode function logic
print("KEY COMPARISON:")
print("Key 1 matches hardcoded key:", key1 == "VlVaYWIwMXJNVk1oYVJuQnJaV3R3QU5WWXlNVlpsYkVScFhZVVJLVGxZeUtVbUZVTUZKS1RWRVprZFZvemNHbFNSYldoU1ZGWmFkMU1kdFVqWlRiV3hZQVltMTBObFpyV21SOVdNREZWVkd4d0tWR0ZyY0ZOV01uRWhPWlcxT1IyRkdSYkU1V01YQmhWa01aU1MwNVdaSE5hQU0zQlNWbTFuTVZSUldhR0ZYYXpsRktVMnhhV0dKck1URVk9")
print("Key 2 matches hardcoded key:", key2 == "VlVaYWIwMXJNVk1oYVJuQnJaV3R3QU5WWXlNVlpsYkVScFhZVVJLVGxZeUtVbUZVTUZKS1RWRVprZFZvemNHbFNSYldoU1ZGWmFkMU1kdFVqWlRiV3hZQVltMTBObFpyV21SOVdNREZWVkd4d0tWR0ZyY0ZOV01uRWhPWlcxT1IyRkdSYkU1V01YQmhWa01aU1MwNVdaSE5hQU0zQlNWbTFuTVZSUldhR0ZYYXpsRktVMnhhV0dKck1URVk9")

# Try to decode with direct algorithm (bypassing the hardcoded check)
print("\nDECODING ATTEMPT EXPLANATION:")
print("Key 1 is the original hardcoded 'problematic' key that directly returns 'insta : nattawatthongthong'")
print("Key 2 is the one generated by the encode function and isn't matched by the hardcoded check")
print("\nThis means key2 likely works through the regular decoding algorithm, not the hardcoded case.")